app = "frontend-blue-morning-132"
primary_region = "ams"

[build]
  dockerfile = "./src/Dockerfile"

[http_service]
  internal_port = 80
  external_port = 80
  force_https = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
