version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Optional, defaults to Dockerfile in the context
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Optional, defaults to Dockerfile in the context
    ports:
      - "5000:5000"