# fly.toml app configuration file generated for app-transactions

app = 'app-transactions'

[build]
  # Reference Docker Compose file directly
  docker_compose_file = "./docker-compose.yml"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3000
  external_port = 80
  force_https = true
