app = "app-transactions"

[build]
  # Reference Docker Compose file directly
  docker_compose_file = "./docker-compose.yml"

[[services]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
