app = "backend-ancient-haze-9586"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 5000
  external_port = 5000

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
