name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chrismalm/frontend:latest
        file: ./frontend/Dockerfile
        context: ./frontend

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chrismalm/backend:latest
        file: ./backend/Dockerfile
        context: ./backend

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="/home/runner/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"
        echo "$FLYCTL_INSTALL/bin" >> $GITHUB_PATH

    - name: Set Fly.io API token
      run: echo "FLY_API_TOKEN set"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}

    - name: Deploy to Fly.io
      run: flyctl deploy --config ./fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}
    - name: Deploy Frontend to Fly.io
      run: flyctl deploy --config ./frontend/fly.toml
  
    - name: Deploy Backend to Fly.io
      run: flyctl deploy --config ./backend/fly.toml