name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          chrismalm/frontend:latest
          chrismalm/backend:latest
        file: |
          ./frontend/src/Dockerfile
          ./backend/src/Dockerfile
        context: ./

    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@v1
      with:
        version: v0.2.125  # Ensure this is the latest version if necessary
    - name: Check Flyctl version
      run: flyctl version
      - name: Check if Flyctl is installed
      run: |
        if ! command -v flyctl &> /dev/null
        then
          echo "Flyctl could not be found"
          exit 1
        else
          echo "Flyctl is installed"
        fi
    - name: Authenticate with Fly.io
      run: flyctl auth token
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}

    - name: Deploy to Fly.io
      run: flyctl deploy --config ./fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}
