name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          chrismalm/frontend:latest
          chrismalm/backend:latest
        file: |
          ./frontend/Dockerfile
          ./backend/Dockerfile
        context: ./

    - name: Install Flyctl
      run: curl -L https://fly.io/install.sh | sh

    - name: Authenticate with Flyctl
      run: flyctl auth token ${{ secrets.FLY_API_TOKEN2 }}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}

    - name: Deploy to Fly.io
      run: flyctl deploy --config ./fly.toml
