name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          chrismalm/frontend:latest
          chrismalm/backend:latest
        file: |
          ./frontend/src/Dockerfile
          ./backend/src/Dockerfile
        context: ./

    - name: Install Flyctl
      run: curl -L https://fly.io/install.sh | sh

    - name: Check Flyctl version
      run: flyctl version

    - name: Check Flyctl PATH
      run: |
        echo $PATH
        if ! command -v flyctl &> /dev/null
        then
          echo "Flyctl could not be found"
          exit 1
        else
          echo "Flyctl is installed"
        fi

    - name: Check Flyctl Authentication
      run: |
        echo "Attempting to authenticate with Flyctl"
        flyctl auth token ${{ secrets.FLY_API_TOKEN2 }}
        flyctl auth whoami

    - name: Deploy to Fly.io
      run: flyctl deploy --config ./fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}
